### PR TITLE
BulkUpdatable: bump version

### PR DESCRIPTION
**Pull request by mockdeep**
Time to release all the new `BulkUpdatable` goodness.

### CODE REVIEW

**Comment by mockdeep** [comment]
[(1) #BulkUpdatable bump version [0.1]](https://trello.com/c/4cSVu3tG/17774-1-bulkupdatable-bump-version-01)

**Comment by kaifius** [comment]
bitmoji

**Comment by kaifius** [comment]
LGTM as long as there are no breaking changes in all the BulkUpdatable updates. FFTMM if that's the case.

Can you add release notes after this is merged?

**Comment by mockdeep** [comment]
Nope, no breaking changes. Will add release notes.

**Pull request merged**
